{% set build = 0 %}
{% set version = '2.5.0' %}

package:
    name: magma
    version: {{version}}

about:
    home: http://icl.cs.utk.edu/magma/
    license: BSD
    summary: 'Matrix Algebra on GPU and Multicore Architectures'

source:
    fn: magma-{{version}}.tar.gz
    url: http://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-{{version}}.tar.gz
    md5: a869dcbc4029a57126e21a6ec4850083

requirements:
    build:
        - openblas

    run:
        - openblas

build:
    number: {{build}}
    string: cuda101_{{build}}
